titre_court: Comment la psychothérapie institutionnelle existe-t-elle aujourd’hui à l’université ?
nom_site: Psychothérapie institutionnelle à l’université
meta_description: Ressources, partenaires et agenda issus du colloque « Comment la psychothérapie institutionnelle existe-t-elle aujourd'hui ? » (Marseille, 2 et 3 octobre 2025).
adresse: |-
  3 rue de Turbigo
  75001 Paris
email: info@nomedominio.com
telephone: +33 (0)1 42 72 60 01
newsletter_url: ""
newsletter_label: Formulaire d'inscription
